// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: dukh.proto

package dukhpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_dukh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dukh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_dukh_proto_rawDescGZIP(), []int{0}
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_dukh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dukh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_dukh_proto_rawDescGZIP(), []int{1}
}

func (x *StopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StatusRequest optionally scopes the response to a single workspace.
// An empty workspace_name returns all workspaces.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceName string                 `protobuf:"bytes,1,opt,name=workspace_name,json=workspaceName,proto3" json:"workspace_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_dukh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dukh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_dukh_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetWorkspaceName() string {
	if x != nil {
		return x.WorkspaceName
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*WorkspaceStatus     `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	ServerVersion string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_dukh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dukh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_dukh_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetWorkspaces() []*WorkspaceStatus {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

func (x *StatusResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// WorkspaceStatus aggregates project health for one workspace.
type WorkspaceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Projects      []*ProjectStatus       `protobuf:"bytes,3,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceStatus) Reset() {
	*x = WorkspaceStatus{}
	mi := &file_dukh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceStatus) ProtoMessage() {}

func (x *WorkspaceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dukh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceStatus.ProtoReflect.Descriptor instead.
func (*WorkspaceStatus) Descriptor() ([]byte, []int) {
	return file_dukh_proto_rawDescGZIP(), []int{4}
}

func (x *WorkspaceStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkspaceStatus) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WorkspaceStatus) GetProjects() []*ProjectStatus {
	if x != nil {
		return x.Projects
	}
	return nil
}

// ProjectStatus aggregates repository health for one project.
type ProjectStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Repositories  []*RepoStatus          `protobuf:"bytes,2,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectStatus) Reset() {
	*x = ProjectStatus{}
	mi := &file_dukh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectStatus) ProtoMessage() {}

func (x *ProjectStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dukh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectStatus.ProtoReflect.Descriptor instead.
func (*ProjectStatus) Descriptor() ([]byte, []int) {
	return file_dukh_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectStatus) GetRepositories() []*RepoStatus {
	if x != nil {
		return x.Repositories
	}
	return nil
}

// RepoStatus describes the health of a single repository.
type RepoStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path             string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	ConfiguredBranch string                 `protobuf:"bytes,3,opt,name=configured_branch,json=configuredBranch,proto3" json:"configured_branch,omitempty"`
	ActualBranch     string                 `protobuf:"bytes,4,opt,name=actual_branch,json=actualBranch,proto3" json:"actual_branch,omitempty"`
	Exists           bool                   `protobuf:"varint,5,opt,name=exists,proto3" json:"exists,omitempty"`
	BranchAligned    bool                   `protobuf:"varint,6,opt,name=branch_aligned,json=branchAligned,proto3" json:"branch_aligned,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RepoStatus) Reset() {
	*x = RepoStatus{}
	mi := &file_dukh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoStatus) ProtoMessage() {}

func (x *RepoStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dukh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoStatus.ProtoReflect.Descriptor instead.
func (*RepoStatus) Descriptor() ([]byte, []int) {
	return file_dukh_proto_rawDescGZIP(), []int{6}
}

func (x *RepoStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RepoStatus) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RepoStatus) GetConfiguredBranch() string {
	if x != nil {
		return x.ConfiguredBranch
	}
	return ""
}

func (x *RepoStatus) GetActualBranch() string {
	if x != nil {
		return x.ActualBranch
	}
	return ""
}

func (x *RepoStatus) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *RepoStatus) GetBranchAligned() bool {
	if x != nil {
		return x.BranchAligned
	}
	return false
}

var File_dukh_proto protoreflect.FileDescriptor

const file_dukh_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"dukh.proto\x12\adukh.v1\"\r\n" +
	"\vStopRequest\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"6\n" +
	"\rStatusRequest\x12%\n" +
	"\x0eworkspace_name\x18\x01 \x01(\tR\rworkspaceName\"\x98\x01\n" +
	"\x0eStatusResponse\x128\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x18.dukh.v1.WorkspaceStatusR\n" +
	"workspaces\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"m\n" +
	"\x0fWorkspaceStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x122\n" +
	"\bprojects\x18\x03 \x03(\v2\x16.dukh.v1.ProjectStatusR\bprojects\"\\\n" +
	"\rProjectStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\frepositories\x18\x02 \x03(\v2\x13.dukh.v1.RepoStatusR\frepositories\"\xc5\x01\n" +
	"\n" +
	"RepoStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12+\n" +
	"\x11configured_branch\x18\x03 \x01(\tR\x10configuredBranch\x12#\n" +
	"\ractual_branch\x18\x04 \x01(\tR\factualBranch\x12\x16\n" +
	"\x06exists\x18\x05 \x01(\bR\x06exists\x12%\n" +
	"\x0ebranch_aligned\x18\x06 \x01(\bR\rbranchAligned2}\n" +
	"\vDukhService\x123\n" +
	"\x04Stop\x12\x14.dukh.v1.StopRequest\x1a\x15.dukh.v1.StopResponse\x129\n" +
	"\x06Status\x12\x16.dukh.v1.StatusRequest\x1a\x17.dukh.v1.StatusResponseB,Z*github.com/vhula/grazhda/dukh/proto;dukhpbb\x06proto3"

var (
	file_dukh_proto_rawDescOnce sync.Once
	file_dukh_proto_rawDescData []byte
)

func file_dukh_proto_rawDescGZIP() []byte {
	file_dukh_proto_rawDescOnce.Do(func() {
		file_dukh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dukh_proto_rawDesc), len(file_dukh_proto_rawDesc)))
	})
	return file_dukh_proto_rawDescData
}

var file_dukh_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_dukh_proto_goTypes = []any{
	(*StopRequest)(nil),     // 0: dukh.v1.StopRequest
	(*StopResponse)(nil),    // 1: dukh.v1.StopResponse
	(*StatusRequest)(nil),   // 2: dukh.v1.StatusRequest
	(*StatusResponse)(nil),  // 3: dukh.v1.StatusResponse
	(*WorkspaceStatus)(nil), // 4: dukh.v1.WorkspaceStatus
	(*ProjectStatus)(nil),   // 5: dukh.v1.ProjectStatus
	(*RepoStatus)(nil),      // 6: dukh.v1.RepoStatus
}
var file_dukh_proto_depIdxs = []int32{
	4, // 0: dukh.v1.StatusResponse.workspaces:type_name -> dukh.v1.WorkspaceStatus
	5, // 1: dukh.v1.WorkspaceStatus.projects:type_name -> dukh.v1.ProjectStatus
	6, // 2: dukh.v1.ProjectStatus.repositories:type_name -> dukh.v1.RepoStatus
	0, // 3: dukh.v1.DukhService.Stop:input_type -> dukh.v1.StopRequest
	2, // 4: dukh.v1.DukhService.Status:input_type -> dukh.v1.StatusRequest
	1, // 5: dukh.v1.DukhService.Stop:output_type -> dukh.v1.StopResponse
	3, // 6: dukh.v1.DukhService.Status:output_type -> dukh.v1.StatusResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dukh_proto_init() }
func file_dukh_proto_init() {
	if File_dukh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dukh_proto_rawDesc), len(file_dukh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dukh_proto_goTypes,
		DependencyIndexes: file_dukh_proto_depIdxs,
		MessageInfos:      file_dukh_proto_msgTypes,
	}.Build()
	File_dukh_proto = out.File
	file_dukh_proto_goTypes = nil
	file_dukh_proto_depIdxs = nil
}
