// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: dukh.proto

package dukhpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DukhService_Stop_FullMethodName   = "/dukh.v1.DukhService/Stop"
	DukhService_Status_FullMethodName = "/dukh.v1.DukhService/Status"
	DukhService_Scan_FullMethodName   = "/dukh.v1.DukhService/Scan"
)

// DukhServiceClient is the client API for DukhService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DukhService exposes workspace health monitoring and server lifecycle control.
type DukhServiceClient interface {
	// Stop requests a graceful shutdown of the dukh server.
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	// Status returns the current health snapshot of all monitored workspaces.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Scan triggers an immediate out-of-cycle workspace rescan.
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
}

type dukhServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDukhServiceClient(cc grpc.ClientConnInterface) DukhServiceClient {
	return &dukhServiceClient{cc}
}

func (c *dukhServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, DukhService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dukhServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DukhService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dukhServiceClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, DukhService_Scan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DukhServiceServer is the server API for DukhService service.
// All implementations must embed UnimplementedDukhServiceServer
// for forward compatibility.
//
// DukhService exposes workspace health monitoring and server lifecycle control.
type DukhServiceServer interface {
	// Stop requests a graceful shutdown of the dukh server.
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	// Status returns the current health snapshot of all monitored workspaces.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// Scan triggers an immediate out-of-cycle workspace rescan.
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	mustEmbedUnimplementedDukhServiceServer()
}

// UnimplementedDukhServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDukhServiceServer struct{}

func (UnimplementedDukhServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedDukhServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedDukhServiceServer) Scan(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedDukhServiceServer) mustEmbedUnimplementedDukhServiceServer() {}
func (UnimplementedDukhServiceServer) testEmbeddedByValue()                     {}

// UnsafeDukhServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DukhServiceServer will
// result in compilation errors.
type UnsafeDukhServiceServer interface {
	mustEmbedUnimplementedDukhServiceServer()
}

func RegisterDukhServiceServer(s grpc.ServiceRegistrar, srv DukhServiceServer) {
	// If the following call panics, it indicates UnimplementedDukhServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DukhService_ServiceDesc, srv)
}

func _DukhService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DukhServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DukhService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DukhServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DukhService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DukhServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DukhService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DukhServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DukhService_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DukhServiceServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DukhService_Scan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DukhServiceServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DukhService_ServiceDesc is the grpc.ServiceDesc for DukhService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DukhService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dukh.v1.DukhService",
	HandlerType: (*DukhServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stop",
			Handler:    _DukhService_Stop_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _DukhService_Status_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _DukhService_Scan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dukh.proto",
}
