// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/workspace.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitWorkspacesRequest) Reset() {
	*x = InitWorkspacesRequest{}
	mi := &file_proto_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitWorkspacesRequest) ProtoMessage() {}

func (x *InitWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*InitWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_proto_workspace_proto_rawDescGZIP(), []int{0}
}

type InitWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []string               `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitWorkspacesResponse) Reset() {
	*x = InitWorkspacesResponse{}
	mi := &file_proto_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitWorkspacesResponse) ProtoMessage() {}

func (x *InitWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*InitWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_proto_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *InitWorkspacesResponse) GetStatuses() []string {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type PurgeWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeWorkspacesRequest) Reset() {
	*x = PurgeWorkspacesRequest{}
	mi := &file_proto_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeWorkspacesRequest) ProtoMessage() {}

func (x *PurgeWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*PurgeWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_proto_workspace_proto_rawDescGZIP(), []int{2}
}

type PurgeWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []string               `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeWorkspacesResponse) Reset() {
	*x = PurgeWorkspacesResponse{}
	mi := &file_proto_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeWorkspacesResponse) ProtoMessage() {}

func (x *PurgeWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*PurgeWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_proto_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *PurgeWorkspacesResponse) GetStatuses() []string {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type GetWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspacesRequest) Reset() {
	*x = GetWorkspacesRequest{}
	mi := &file_proto_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspacesRequest) ProtoMessage() {}

func (x *GetWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_proto_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkspacesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*Workspace           `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspacesResponse) Reset() {
	*x = GetWorkspacesResponse{}
	mi := &file_proto_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspacesResponse) ProtoMessage() {}

func (x *GetWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*GetWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_proto_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkspacesResponse) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AbsolutePath  string                 `protobuf:"bytes,4,opt,name=absolute_path,json=absolutePath,proto3" json:"absolute_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_proto_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_proto_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *Workspace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workspace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workspace) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Workspace) GetAbsolutePath() string {
	if x != nil {
		return x.AbsolutePath
	}
	return ""
}

var File_proto_workspace_proto protoreflect.FileDescriptor

const file_proto_workspace_proto_rawDesc = "" +
	"\n" +
	"\x15proto/workspace.proto\x12\tworkspace\"\x17\n" +
	"\x15InitWorkspacesRequest\"4\n" +
	"\x16InitWorkspacesResponse\x12\x1a\n" +
	"\bstatuses\x18\x01 \x03(\tR\bstatuses\"\x18\n" +
	"\x16PurgeWorkspacesRequest\"5\n" +
	"\x17PurgeWorkspacesResponse\x12\x1a\n" +
	"\bstatuses\x18\x01 \x03(\tR\bstatuses\"(\n" +
	"\x14GetWorkspacesRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"M\n" +
	"\x15GetWorkspacesResponse\x124\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x14.workspace.WorkspaceR\n" +
	"workspaces\"s\n" +
	"\tWorkspace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12#\n" +
	"\rabsolute_path\x18\x04 \x01(\tR\fabsolutePath2\x97\x02\n" +
	"\x10WorkspaceService\x12U\n" +
	"\x0eInitWorkspaces\x12 .workspace.InitWorkspacesRequest\x1a!.workspace.InitWorkspacesResponse\x12X\n" +
	"\x0fPurgeWorkspaces\x12!.workspace.PurgeWorkspacesRequest\x1a\".workspace.PurgeWorkspacesResponse\x12R\n" +
	"\rGetWorkspaces\x12\x1f.workspace.GetWorkspacesRequest\x1a .workspace.GetWorkspacesResponseB%Z#github.com/vhula/grazhda/dukh/protob\x06proto3"

var (
	file_proto_workspace_proto_rawDescOnce sync.Once
	file_proto_workspace_proto_rawDescData []byte
)

func file_proto_workspace_proto_rawDescGZIP() []byte {
	file_proto_workspace_proto_rawDescOnce.Do(func() {
		file_proto_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_workspace_proto_rawDesc), len(file_proto_workspace_proto_rawDesc)))
	})
	return file_proto_workspace_proto_rawDescData
}

var file_proto_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_workspace_proto_goTypes = []any{
	(*InitWorkspacesRequest)(nil),   // 0: workspace.InitWorkspacesRequest
	(*InitWorkspacesResponse)(nil),  // 1: workspace.InitWorkspacesResponse
	(*PurgeWorkspacesRequest)(nil),  // 2: workspace.PurgeWorkspacesRequest
	(*PurgeWorkspacesResponse)(nil), // 3: workspace.PurgeWorkspacesResponse
	(*GetWorkspacesRequest)(nil),    // 4: workspace.GetWorkspacesRequest
	(*GetWorkspacesResponse)(nil),   // 5: workspace.GetWorkspacesResponse
	(*Workspace)(nil),               // 6: workspace.Workspace
}
var file_proto_workspace_proto_depIdxs = []int32{
	6, // 0: workspace.GetWorkspacesResponse.workspaces:type_name -> workspace.Workspace
	0, // 1: workspace.WorkspaceService.InitWorkspaces:input_type -> workspace.InitWorkspacesRequest
	2, // 2: workspace.WorkspaceService.PurgeWorkspaces:input_type -> workspace.PurgeWorkspacesRequest
	4, // 3: workspace.WorkspaceService.GetWorkspaces:input_type -> workspace.GetWorkspacesRequest
	1, // 4: workspace.WorkspaceService.InitWorkspaces:output_type -> workspace.InitWorkspacesResponse
	3, // 5: workspace.WorkspaceService.PurgeWorkspaces:output_type -> workspace.PurgeWorkspacesResponse
	5, // 6: workspace.WorkspaceService.GetWorkspaces:output_type -> workspace.GetWorkspacesResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_workspace_proto_init() }
func file_proto_workspace_proto_init() {
	if File_proto_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_workspace_proto_rawDesc), len(file_proto_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_workspace_proto_goTypes,
		DependencyIndexes: file_proto_workspace_proto_depIdxs,
		MessageInfos:      file_proto_workspace_proto_msgTypes,
	}.Build()
	File_proto_workspace_proto = out.File
	file_proto_workspace_proto_goTypes = nil
	file_proto_workspace_proto_depIdxs = nil
}
